name: test

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        include: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: echo "value=$(printf -- '%s' '[{"value":1},{"value":2},{"value":3}]')" >> "$GITHUB_OUTPUT"
      - run: echo '${{ matrix.value }}'
