name: test

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node-version: 16
          - os: ubuntu-latest
            node-version: 18
          - os: ubuntu-latest
            node-version: 20
    steps:
      - id: matrix
        run: echo "value=$(printf -- '%s' '${{ toJSON(strategy.matrix) }}')" >> "$GITHUB_OUTPUT"
      - run: echo '${{ steps.matrix.outputs.value }}' | tee matrix.json
      - run: jq . matrix.json
